### ISSUE TITLE
Translation question

### ISSUE THREAD

**Issue by debyos** [plepe/OpenStreetBrowser#102]
Dear All,

what do "available branches" mean? (I.e. how should I translate it?)
Thanks!

_Gábor_
*

![available_branches](https://user-images.githubusercontent.com/26843901/56294877-1b8a1400-612c-11e9-96af-c15ccc1136c3.png)

**Comment by plepe** [comment]
I a source code repository you can create branches - these are often used for developing new features before merging them back to the "master" branch. Here for example the list of branches for the main categories: https://github.com/plepe/openstreetbrowser-categories-main/branches

More about branches: https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

I hope it is now clearer?

**Comment by plepe** [comment]
Sorry, accidentally closed.

**Comment by debyos** [comment]
OK, vielen Dank!
