### ISSUE TITLE
Marker-Line: dashed lines

### ISSUE THREAD

**Issue by plepe** [plepe/OpenStreetBrowser#109]
Hufkratzer [reported](https://wiki.openstreetmap.org/wiki/Talk:OpenStreetBrowser/Howto_Categories#Dashed_lines): 

> Can markerLine({ 'width': 2, color: ...}) draw dashed lines? How? Is this function documented? Where? Icons can be used for that, but it's a bit cumbersome.

**Comment by plepe** [comment]
@Hufkratzer 

I made some updates to the code and added documentation, but it is still in the development branch:
https://github.com/plepe/OpenStreetBrowser/blob/markers-improve/doc/Icons.md#markers

These things are only available after merging the branch:
* The `<img data-src="marker:...">` syntax
* Multiple symbol syntax for circle and pointer

**Comment by Hufkratzer** [comment]
Thanks, dashArray is what I was interested in and that already seems to work.

**Comment by plepe** [comment]
The branch has now been merged :-)

So, the documentation URL is now: https://github.com/plepe/OpenStreetBrowser/blob/master/doc/Icons.md
