### ISSUE TITLE
Weblate warning "Could not parse translation files."

### ISSUE THREAD

**Issue by Hufkratzer** [plepe/OpenStreetBrowser#112]
In weblate there is a new warning: "

> Weblate could not parse the translation files while updating the translations. ...

See https://weblate.openstreetbrowser.org/projects/openstreetbrowser/osm-tags/#alerts

**Comment by plepe** [comment]
I had some problems with a merge. Fixed, but I had to reset the package sources. I think the last view changes were discarded ... Sorry!
