### ISSUE TITLE
Translation of "heritage"

### ISSUE THREAD

**Issue by IgorEliezer** [plepe/OpenStreetBrowser#114]
Example: https://openstreetbrowser.org/#historic/r9963374&map=18/-23.44557/-46.91461&categories=historic
(The "heritage" under the picture in the popup)

I couldn't find the source string for "heritage", but I found "heritage=0" (zero, is it valid?), "heritage=2", "heritage=4" and "heritage=8".

Or, the popup is buggy.

**Comment by plepe** [comment]
The string below the picture is "historic=heritage" (which was not in the translation files either).

I also added the key heritage (with the strings from heritage=0, which I removed) and added heritage=1.

**Comment by IgorEliezer** [comment]
The word "heritage" still appears untranslated.

![image](https://user-images.githubusercontent.com/4673289/65088426-adbe6e80-d98f-11e9-8c22-b7ce426e2e25.png)

https://www.openstreetbrowser.org/#historic/r9963374&map=18/-23.44446/-46.91504&categories=historic

Interface language: pt-BR (Brazilian Portuguese)

**Comment by plepe** [comment]
Sorry, I thought I had added the tag `historic=heritage`, apparently I did not. Added it now.

**Comment by IgorEliezer** [comment]
Found it. Thank you.

Tag:heritage=0 is still there.

**Comment by plepe** [comment]
Oh, I just changed the key, not the description ;-) Fixed.

**Comment by IgorEliezer** [comment]
Sorry but the string "heritage" below the picture is still untranslated.

**Comment by plepe** [comment]
I forgot to clear the caches :-(

Now it works: 
![Screenshot_2019-09-19 OpenStreetBrowser](https://user-images.githubusercontent.com/249012/65222646-cc238780-dabf-11e9-977b-88857b96f9da.png)
