### ISSUE TITLE
[object Object]

### ISSUE THREAD

**Issue by IgorEliezer** [plepe/OpenStreetBrowser#121]
Some categories are displaying "[object Object]" instead of blank or something that was supposed to be.

Example: 
* suburbs whose population tag is missing: https://openstreetbrowser.org/#places/n4135957535&map=17/-23.64116/-46.52610&categories=places
* schools without operator: https://openstreetbrowser.org/#education/w361471969&map=18/-23.65525/-46.53052&categories=education
* public buildings without operator: https://openstreetbrowser.org/#public/w152910427&map=17/-23.65772/-46.53167&categories=public

etc.

**Comment by plepe** [comment]
Thanks for notifying! After some digging, I found the problem. It's a problem in the [Twig.js module](https://github.com/twigjs/twig.js) which has already been resolved on the master branch (there's no release yet). Twig.js returns an object, if the resulting string is empty.

I updated the Twig.js version to the master branch, the problem does not appear any more.

**Comment by IgorEliezer** [comment]
Thank you.
