### ISSUE TITLE
Ignore private swimming pools

### ISSUE THREAD

**Issue by pangoSE** [plepe/OpenStreetBrowser#122]
See https://www.openstreetbrowser.org/#leisure/w546924815&map=17/62.62219/17.91993&categories=leisure,wikipedia
This pool is tagged access=private and I think we should ignore those.

**Comment by plepe** [comment]
Hmm, there's a special "Swimming and Bathing" category, which ignores private swimming pools. The leisure category just contains everything tagged leisure=* ...

Maybe the Leisure category should ignore all private things? Or is there a special reason just to ignore private swimming pools?

**Comment by plepe** [comment]
Any thought on the issue?

**Comment by trapicki** [comment]
I find private swimming pools less interresting, in fact annoying and distracting.

In general, when using OpenStreetbrowser, first I'm interested in things that I can use by myself. If I want to know more in depth details, I'd like to activate them separately. 

In this very case, I'd prefer public accessible leisure=*, with a subcategory like "including private".

**Comment by plepe** [comment]
The leisure category now excludes all private objects by default. There's a filter to change this behaviour (resp. query for specific access-values). There will be an announcement about this soon[tm].

**Comment by Hufkratzer** [comment]
I think "publicly accessible" should show anything with access=yes and also anything with without an access tag; in other words, it should include "empty value". access=yes is usually omitted.

**Comment by plepe** [comment]
The default (currently) for the leisure-category is, to exclude access=private. All other access values and also a missing access-tag are included. The filter value is labelled "non-private".

Other values include public, permissive, customers, unknown, discouraged. I guess you could discuss which values should by default be included, but I would rather say yes.

**Comment by dpriskorn** [comment]
Nice 😀
