### ISSUE TITLE
Option to set editor

### ISSUE THREAD

**Issue by stefanct** [plepe/OpenStreetBrowser#123]
I detest ID and would thus prefer to be able to edit via Josm. It would be nice to be able to change the behavior of the edit link available in the popups to facilitate this directly.

**Comment by plepe** [comment]
Good idea! I jumped right in and implemented that, it will be included in the next release! -> #124

**Comment by plepe** [comment]
Done. -> https://blog.openstreetbrowser.org/node/78

Feel free to re-open the issue if you have comments!

**Comment by stefanct** [comment]
I think you broke it somehow? (and btw users cannot re-open issues AFAICT ;)

**Comment by plepe** [comment]
Thanks for notifying! I already found the problem - it's sleazy coding and babel. It worked in my development environment, but apparently I never tested it in the live system. Babel converts the code and makes it more strict - and I forgot to declare a variable.

See 8d915077b01f4575ee9d04bdaa6449d87eb83739

Fixed. Will be online with the next update (today?).

**Comment by stefanct** [comment]
Ah, thanks for the fix! I thought I have used/tested it already, but apparently testing is not possible for users without roll-out so I probably had no need to edit via OSB since then and never tested it. :)

It's certainly not necessary but if you see an effortless way to inform reporters about roll-outs of changes that fix their problems (similar to the emails in Debian's bug tracker) that wouldn't happen again. But I doubt that there is a bot for that (only for notifications about commits that close an issue).

**Comment by plepe** [comment]
The fix is now online!

**Comment by stefanct** [comment]
LGTM, thx.
