### ISSUE TITLE
Add Wikidata link

### ISSUE THREAD

**Issue by IgorEliezer** [plepe/OpenStreetBrowser#126]
Is it possible to make the Wikidata value clickable in Attributes?

![image](https://user-images.githubusercontent.com/4673289/82891434-1ea52580-9f24-11ea-8e01-f886312b5438.png)

**Comment by plepe** [comment]
Yes, I already have code for this. I will try to get it merged soon :-)

**Comment by plepe** [comment]
See #127

**Comment by IgorEliezer** [comment]
So that would include the other kinds of wikidata tags, such as `subject:wikidata`, `artist:wikidata`, `architect:wikidata` and so on. :+1:

**Comment by plepe** [comment]
The changes are already live! An announcement on the blog will follow.
