### ISSUE TITLE
Unnamed items should get better name

### ISSUE THREAD

**Issue by trapicki** [plepe/OpenStreetBrowser#132]
Currently, if an item has no proper name tag, it is named "unnamed" (or the translation of "unnamed") along with the category. This is frustrating, because it clutters the result list and shows content without much information and thus value instead of something more useful.

I'd suggest to show the still available most valuable information of the item instead, that would be the category, with some hint that the item does not have a proper name. The hint could be showing the text in italics or a little gray, or with the extra information "(unnamed)". In best case this hint includes a link with an opportunity to add the name, maybe with an annotation in OSM.

![Bildschirmfoto 2020-08-30 um 16 08 42](https://user-images.githubusercontent.com/1251121/91661302-7e8b0980-eadb-11ea-8dbe-f424b7b2f89c.png)

**Comment by plepe** [comment]
Hmm, I see your point and this is something which I'm also not too happy about. I think the most reasonable would be to show the value of leisure (in that case "slipway" resp. "Slipanlage"). But then this is what is shown as description in most categories ...

Or, do you think to show "Leisure" (Freizeit) would make sense?

**Comment by trapicki** [comment]
Thinking about it, looking in the categories code and structure, I think the distinction between title and description and going with title first and more prominent and then adding a description with usually the category in it forces the inconvenient decision to have something in the title, but if there is nothing like a title, it defaults to "unknown", which is akward.

Things that do not have anything interesting with them should only show what they are, nothing more. A waste basket is a waste basket, nothing more. Sometimes it has a ash tray or a bag dispenser as an extra, which is noteworth, still, no name, and I do not expect some.
Searching for a doctor, my first concern is to distinguish them from defibriliators, hospitals and veterinaries, then I'd like to know if she is the kind I need (teeth, eyes, kidney...), then the name, opening hours, address, phone number, website etc.
For slipways I'd like to know that it's a slipway, if I can use it (public?), and how (size, surface).

Putting all that in to distinct fields is hard: what to go where? I'd suggest to not use the description for the category, this yields the "empty" title for many cases.
I'd try with: Info: Category with maybe a sub-category (like with doctors), then the name if available in italics. If the name already includes the category (think hotel, or the Golfplatz (golf course) from the example) and starts with the category in the display language, leave out the category in front.
For the description simple things like access (the slipways in the example are both private), ref, operator (with "Operator: "), info if available, opening hours, phone nr/website, road surface or track grade, capacity (parking space) etc. 
I'd drop the description (empty) if there is nothing more to say. A fireplace is a fireplace, I don't need more. Space is precious...

Maybe I'll manage to get an example category that will demonstrate this.

**Comment by plepe** [comment]
Hmm, I totally see your point.

There's this beautiful OSM page https://bexhill-osm.org.uk/, which has been an inspiration to latter versions of OpenStreetBrowser. It has lists too, and these show first the type of objects and then the name below (I guess, this could also be empty). So, similar what you are proposing.

Question is how to proceed with categories, where the description is not the type of object, but a value, e.g. the speed "30 km/h".

We could have: Type (from Amenity or Leisure, ...), Title (from name or operator or ref), Description (from additional tags depending on the category, e.g. cuisine, capacity, maxspeed, ...).

Examples:

| Type | Title | Description |
|--------|-------|-----------------|
| Fast-Food Restaurant | McDonalds | burgers
| Unclassified Road | | 50 mph
| Waste Basket | |
| Public telephone | Telekom Austria |
| Doctor | Dr. Sommer | psychiatrist |
| Bicycle parking | | Capacity: 30, roofed

Do you think, this is the way forward?

**Comment by plepe** [comment]
Check this out: https://xover.mud.at/~skunk/openstreetbrowser/

I just adapted the following categories:
* Leisure -> Gastro
* Leisure -> Shop
* Leisure -> Leisure
* Services -> Public
* Transport -> Car -> Maxspeed

What do you say?

**Comment by plepe** [comment]
So?

**Comment by trapicki** [comment]
Great! 
Much more readable for me, even if it's not as sleek in design as before (no offense).

Any other opinions?

**Comment by plepe** [comment]
Really? What about these rounded borders? Do you have any ideas, how to improve matters? You are welcome to share mock-ups ;-)

**Comment by trapicki** [comment]
Comparing side by side I finally noticed the highlighting of entries, which is of great benefit, so natural I didn't notice.

Regarding the texts:
I'd change in 

- the list:
  -  Type and description in first line, gray, italic
  -  Title: black regular
  - ![Bildschirmfoto 2020-09-19 um 22 49 52](https://user-images.githubusercontent.com/1251121/93689076-58013280-facb-11ea-8569-53117658b9c0.png) 

- the pop-up:
  - Type and description in first line, font-size: smaller, description italic
  - Title: black regular, size is good
  - ![Bildschirmfoto 2020-09-19 um 22 46 04](https://user-images.githubusercontent.com/1251121/93689087-72d3a700-facb-11ea-922d-b0155d599e27.png)
Otherwise nothing I would change.

**Comment by plepe** [comment]
Looks good. I'm still considering the naming. Because, until now, we had 'title' and 'description'. In the examples above I named it 'title' and 'type'. (so in fact, I renamed the 'description' to 'type').

In most categories I would need to rename 'description' to 'type', which I'd like to avoid. There are just a few categories, where the description is something else, e.g. the speed in maxspeed, or in the children category some items (e.g. kids_area in restaurants -> right now it reads "Kids Area / Title" -> I think it would make more sense to write "Restaurant / Title / Kids Area" - it could show other amenities as well, e.g. "Kids Area, Toilets with changing table").

So, I would leave "description" as is (resp. rewrite the categories, which are different), "title" as is and introduce a third option. What do you think, should I name it? "details"?

**Comment by trapicki** [comment]
"descriptions", "title" and "details" seem good to me.

If someone would create a new category, would this be a agreeable summary?
- Description: what is it, by what could it be grouped
- Title: the proper name, if applicable
- Details: All the details that make it a specific thing
More information ("properties") in the popup

**Comment by plepe** [comment]
Finally online: https://blog.openstreetbrowser.org/node/82
