### ISSUE TITLE
No more graphical preview on www.openstreetbrowser.org/dev?

### ISSUE THREAD

**Issue by Hufkratzer** [plepe/OpenStreetBrowser#145]
I wasn't active in https://www.openstreetbrowser.org/dev for about a year. Back then, if I remember it correctly, when editing a json file, on the "Preview Changes" tab there was some preview of the file in OSB, so that I could quickly check if the changes made sense before saving them. Unfortunately, this functionality doesn't seem to be available anymore. Now in the "Preview Changes" tab I only get a diff of the source code, and to test the new version I have to save it first and then load it on https://openstreetbrowser.org, what is quite tedious.

Is this preview functionality really gone? Or have I just forgotten something?

**Comment by plepe** [comment]
Recently, after upgrading the server operating system, the dev-page stopped working. I had to update the software (Gitea), which was quite difficult. It's not the newest version yet and does not include the graphical editor, but at least it works. I'll try to get the page to work soon, promise!

**Comment by plepe** [comment]
Now it's the most up-to-date version, I just have to re-integrate the graphical editor :-)

**Comment by plepe** [comment]
I guess this will take quite some time, I'm falling into a rabbit hole, trying to re-integrate the editor. I'll keep you updated!

**Comment by Hufkratzer** [comment]
Oh, sorry for you. No problem for me, it's not urgent.

**Comment by plepe** [comment]
The editor is still not working again, but now it's possible to write categories in YAML, which is much easier than JSON. Here's a little tutorial: https://github.com/plepe/OpenStreetBrowser/blob/master/doc/CategoryAsYAML.md

**Comment by Hufkratzer** [comment]
Together with the custom categories (v5.2) this works great. I can now work with OSB without the old graphical preview. Feel free to close this issue if you want.

**Comment by plepe** [comment]
That's good to hear! I also love writing categories in YAML :-)
