### ISSUE TITLE
"More categories" has more spam than useful content

### ISSUE THREAD

**Issue by opk12** [plepe/OpenStreetBrowser#146]
"More categories" has more spam than useful content.

**Comment by JesseWeinstein** [comment]
Yeah, it needs a higher barrier to entry; see https://www.openstreetbrowser.org/dev/explore/repos . At a minimum, the existing spam should get hidden/removed.

**Comment by JesseWeinstein** [comment]
It looks like the earliest spam was about a year ago, and all the ones up till around May 2021 have been removed (although they still show up on the list I mentioned above, but I don't think they show up in "More categories"). It looks like there are about 120 more to remove.

**Comment by plepe** [comment]
You are right, sorry about not doing something about this earlier. I will look into this issue in the upcoming days.

**Comment by JesseWeinstein** [comment]
Totally understand -- thank you for the making all this available!

**Comment by JesseWeinstein** [comment]
Still needs cleaning up. It's not clear if the 120 mentioned in December are still there or not.

**Comment by plepe** [comment]
Done. Now, only repositories with at least one file are listed.

**Comment by JesseWeinstein** [comment]
Yep, https://www.openstreetbrowser.org looks clean now -- thank you! I dunno if you want to remove the spam from https://www.openstreetbrowser.org/dev/explore/repos or not.

**Comment by plepe** [comment]
Yes, I want. Let's see if and when I can find time to do that ...
