### ISSUE TITLE
Descriptions vs names

### ISSUE THREAD

**Issue by oldenough** [plepe/OpenStreetBrowser#150]
When looking at Japanese place names, historically the name:en= has been used to either give a transliteration of the name or a translation of the name, depending on which the editor has deemed most useful.  Transliteration is nowadays discouraged, but because names written in kanji (characters) can often be transliterated in multiple often wildly different ways, many have continued to supply them.  That leaves the problem of what to do with translations.  If the name has been supplied as the characters for "bell tower" just supplying a transliteration or letting a transliteration engine do its thing, doesn't really help.  The wiki makes it pretty clear that the description should supply the translation of "Bell Tower" or "Head Abbot's Quarters".  Is there a solution to this problem that could be used on the OpenStreetBrowser?

**Comment by plepe** [comment]
Huh, I don't know? What about 'int_name'? Couldn't there be a tag for 'transliterated name'?

**Comment by plepe** [comment]
I'm a bit confused about your request. Can you suggest a solution for the problem?

**Comment by plepe** [comment]
As you did not elaborate on this issue, I'm closing this now. You are welcome to re-open it, if you have further information.
