### ISSUE TITLE
Query problem

### ISSUE THREAD

**Issue by ivanbranco** [plepe/OpenStreetBrowser#162]
I can't use the website since I keep getting this error: 
![image](https://user-images.githubusercontent.com/94002623/198036308-c5f31970-099e-4c56-842b-b1b567f0f172.png)
I'm using Google Chrome v107.0.5304.63 (Official build 64 bit)

**Comment by ivanbranco** [comment]
Uhm, seems like is fixed now. I close it.

**Comment by plepe** [comment]
Yes, I came about that bug myself, and fixed it right away :-)
