### ISSUE TITLE
Request for Wikipedia gives busstops

### ISSUE THREAD

**Issue by Eebie** [plepe/OpenStreetBrowser#166]
I made a request for Wikipedia: https://www.openstreetbrowser.org/#wikipedia/n2534847783&map=16/51.2617/5.4775&categories=wikipedia  
And it showed the busstops in the area.

**Comment by plepe** [comment]
Yes, that's right. The category includes `*:wikidata` features. The item that you showed has an `operator:wikidata` and a `network:wikidata` tag.
