### ISSUE TITLE
YAML import for testing and development

### ISSUE THREAD

**Issue by treestryder** [plepe/OpenStreetBrowser#167]
Thank you for OpenStreetBrowser.

Not sure if this would even be possible, but it would be nice if there were a way to import YAML files for testing and development. This would make it possible to work on a category without NPM, Git and the like.

**Comment by treestryder** [comment]
Never mind. I found the relatively painless option already offered.
https://wiki.openstreetmap.org/wiki/OpenStreetBrowser/Howto_Categories

**Comment by plepe** [comment]
This link is not really up-to-date. It still works, but the inline editor is no longer available.

On the other hand, you can develop categories without leaving OpenStreetBrowser: https://blog.openstreetbrowser.org/node/86

When you are finished with the category, you can still save it on https://www.openstreetbrowser.org/dev (the link from the Howto above).

**Comment by treestryder** [comment]
@plepe That is what I was looking for. Thank you.
