### ISSUE TITLE
Change Marker Color

### ISSUE THREAD

**Issue by treestryder** [plepe/OpenStreetBrowser#173]
It is hard to see icons, particularly multicolor icons, against the red fill color used for markers by default. Is there a way for a category to change this?

**Comment by plepe** [comment]
Yes, you have to set the `markerSymbol` and `listMarkerSymbol`. E.g. `{{ markerPointer({ fillColor: '#ffffff' }) }}` resp. `{{ markerCircle({ fillColor: '#ffffff' }) }}`.

See also the https://github.com/plepe/OpenStreetBrowser/blob/master/doc/Tutorial.md for some examples.

**Comment by treestryder** [comment]
Oh, and I found that setting them to null, or empty in YAML removes them. Which will be handy in some cases.

**Comment by plepe** [comment]
I added the information about the `fill` parameter to the documentation: https://github.com/plepe/OpenStreetBrowser/commit/83879b88f453b5f0ae93ef68d500ead225c5123b

**Comment by plepe** [comment]
(The change about supporting the `fill` parameter resulted in the transparent markers)
