### ISSUE TITLE
Export only filtered items

### ISSUE THREAD

**Issue by ivanbranco** [plepe/OpenStreetBrowser#178]
Hi, as mentioned [here](https://community.openstreetmap.org/t/new-quality-control-categories-in-openstreetbrowser/4121/21): if I in “Culture - Media/Wikidata” I use the “category: no image/wikimedia_commons OR wikidata without image” filter and then I export the data, the exported file contains all “Culture - Media/Wikidata”, not the filtered ones only.

**Comment by plepe** [comment]
Thanks for catching this bug. Items which were only excluded from category logic (the "exclude" property) were not filtered. Fixed: dae2b4c1f684a368ebbdcc03eb7522caa6abac0a
