### ISSUE TITLE
Translation text that hasn't updated yet

### ISSUE THREAD

**Issue by IgorEliezer** [plepe/OpenStreetBrowser#186]
Hello,

The Brazilian Portuguese translation text for ["Planning and Construction"](http://weblate.openstreetbrowser.org/translate/openstreetbrowser/main-categories/pt_BR/?checksum=c0d00a8bdd33814c), under "Infrastructure", has been available for a good long while, however the item on the menu is still in English.

![image](https://github.com/plepe/OpenStreetBrowser/assets/4673289/54840843-a0ea-4128-a5c1-d5d00fd2d603)

**Comment by plepe** [comment]
Thanks for pointing me to this problem. I solved it: f474d526c292445e40726ca560216d586c6ef4f0

**Comment by IgorEliezer** [comment]
Thank you. :)
