### ISSUE TITLE
Wrong translation for "spring" in French

### ISSUE THREAD

**Issue by Nekzuris** [plepe/OpenStreetBrowser#200]
I was looking for "Source" (Spring) but couldn't find the filter because it's wrongly translated as "Ruisseau" (Stream).
![image](https://github.com/user-attachments/assets/1f971a28-e98f-4645-8e77-c9cf8d0326d2)
I quickly looked into the code but didn't find where the translation comes from to fix it.

**Comment by plepe** [comment]
The translations can be edited here: https://weblate.openstreetbrowser.org/projects/openstreetbrowser/

It's the "OpenStreetMap Tags" repository. 

Here's the direct link to natural=spring: https://weblate.openstreetbrowser.org/translate/openstreetbrowser/osm-tags/fr/?checksum=7bcef9fc25d75a27

**Comment by Nekzuris** [comment]
Okay thanks, I fixed it.
It might be wise to put a link to this project in the README.
Any reason for not using the more complete iD translation on Transifex?

**Comment by plepe** [comment]
I will check, if I can use the Transifex translation.

**Comment by plepe** [comment]
I added some links to the top section of the README on https://github.com/plepe/OpenStreetBrowser. What do you think?
