### ISSUE TITLE
Request: Add locale parameter in web address for sharing

### ISSUE THREAD

**Issue by IgorEliezer** [plepe/OpenStreetBrowser#40]
Hello,

I'd like to share a link from OSB with other people but not everyone is proficient in English so that they can easily navigate to options to change the language themselves.

I propose OSB could have a locale parameter, such as `?locale=xx-XX` (e.g.: www.openstreetmap.org/?locale=pt-BR#map=18/-23.05041/-47.83677) or `?lang=xx` (used in OpenRailwayMap).

Regards. :)

**Comment by plepe** [comment]
OpenStreetBrowser tries to detect a suiting browser language. I introduced a 'lang' parameter in 820e00436b22acc91a324a36376fe31c1195f5fb, so now you can force a language. Use lower-cases, e.g. https://openstreetbrowser.org/?lang=pt-br

**Comment by IgorEliezer** [comment]
Oh, that's fancy

https://openstreetbrowser.org/?lang=pt-br&map=18/-23.05041/-47.83677
https://openstreetbrowser.org/?lang=en&map=18/-23.05041/-47.83677.
https://openstreetbrowser.org/?lang=es&map=18/-23.05041/-47.83677.


Thank you! :+1:

**Comment by plepe** [comment]
You are welcome :)
