### ISSUE TITLE
Broken Wikimedia Commons image thumbnail

### ISSUE THREAD

**Issue by IgorEliezer** [plepe/OpenStreetBrowser#41]
I have this small church ([OSM](https://www.openstreetmap.org/way/535023609), [OSB](https://openstreetbrowser.org/#map=20/-23.03912/-47.88918&categories=religion)) which has an image linked to Wikimedia Commons but the image thumbnail is broken.

![osb bug](https://user-images.githubusercontent.com/4673289/38054533-a421476a-32ad-11e8-8a72-f5fe7de4f072.png)

The Wikimedia Commons image: https://commons.wikimedia.org/wiki/File:Capela_S_Ant%C3%B4nio_-Maristela_240710_REFON_23.JPG

I've tried `image=File:Capela_S_Antônio_-Maristela_240710_REFON_23.JPG` and `image=File:Capela_S_Ant%C3%B4nio_-Maristela_240710_REFON_23.JPG` and many other forms, as you can see in [the history](https://www.openstreetmap.org/way/535023609/history). At least the 1st form opens the Wikimedia Commons but the others returned error.

**Comment by plepe** [comment]
Before, I used the thumb.php script from Wikimedia Commons. Unfortunately this script has some limitations, e.g. when the maximum resolution is lower as the requested resolution, it will return 404 (which happened in your case). It will even sometimes return 404 even though the requested resolution is lower than the maximum.

So I decided to internally load the description page (e.g. https://commons.wikimedia.org/wiki/File:Capela_S_Ant%C3%B4nio_-Maristela_240710_REFON_23.JPG) and grep for the url of the preview image there.

If you notice any other missing images, please report.
