### ISSUE TITLE
Feature Request_ Suuport (bike) Charging Stations

### ISSUE THREAD

**Issue by lintux** [plepe/OpenStreetBrowser#45]
Hi,
would be great to see eBike Charging stations under Transportation -> Cycling (Same of course for Cars, etc.)

BR
Stephan

**Comment by plepe** [comment]
Good idea. Added in plepe/openstreetbrowser-categories-main@80a07e84aae0c46af5ab4ecb13827a598bca20a4

Also added translations (at least for English and German): plepe/openstreetmap-tag-translations@00eb8cd1ca4d316e3217da61fe3361eee8ddaa57

**Comment by lintux** [comment]
Thanks for the quick Turnaround. One comment - seems like Bike-Charging
stations under Transportation -> Cycling -> Amenities show only up at a
very late Zoom level .. maybe too late for someone deperately looking
for power ;-)

Someting to improve?

BR

Stephan


Am 20.05.2018 um 12:11 schrieb Stephan Bösch-Plepelits:

**Comment by plepe** [comment]
I guess you are right - what zoom level do you suggest? (You can see the zoom level in the URL, e.g. #map=14/48.2/16.4) <- zoom level 14.

**Comment by lintux** [comment]
I would suggest zoom level 12 or 13 for the cycling amenities ..

BR Stephan

Am 21. Mai 2018 21:11:36 MESZ schrieb "Stephan Bösch-Plepelits" <notifications@github.com>:

**Comment by plepe** [comment]
z13 is fitting, because some other amenities (like shops) also start there. Changed.
