### ISSUE TITLE
Add Wikipedia link in the POI pop-up

### ISSUE THREAD

**Issue by IgorEliezer** [plepe/OpenStreetBrowser#53]
Using this as [example](https://openstreetbrowser.org/#wikipedia/n368180138&map=17/-23.04969/-47.83582&categories=wikipedia), the pop-up already has `name`, `image`, _show details_ and _edit_, I would also add "_W_ **Wikipedia:** {wikipedia link}".

**Comment by plepe** [comment]
Good idea. Fixed in plepe/openstreetbrowser-categories-main@f10910dc63407ccf9122cc298bd09acbad2609e9 .

In contrast to the wikipedia abstract in 'show details', it won't search for the wikipedia article in your language (if available).
