### ISSUE TITLE
emergency=phone shown as "null" in pop-up

### ISSUE THREAD

**Issue by IgorEliezer** [plepe/OpenStreetBrowser#55]
Example: https://openstreetbrowser.org/#emergency/n5197532165&map=16/-23.0560/-47.8252&categories=emergency

You see "Rodovias do Tietê" as operator, but its type/class shows "null" instead of "Emergency phone" , although [there's a translation for that](https://github.com/plepe/openstreetmap-tag-translations/blob/master/tags/pt-br.json#L402).

In comparison, "[Hospital](https://openstreetbrowser.org/#emergency/w534376046&map=16/-23.0530/-47.8282&categories=emergency)" (amenity=hospital + emergency=yes) and "[Police](https://openstreetbrowser.org/#emergency/w536297143&map=16/-23.0514/-47.8386&categories=emergency)" (amenity=police) are classified correctly.

**Comment by plepe** [comment]
Thanks for notifying! Fixed in plepe/openstreetbrowser-categories-main@52d041e50ab77f7e25338c83ba50cfe70c6b9126
