### ISSUE TITLE
Add translation for "payment:*" and "generator:source"

### ISSUE THREAD

**Issue by IgorEliezer** [plepe/OpenStreetBrowser#56]
There are two tags which I'm not sure how to add myself as they are "colon" compounded, as follows:

1. `payment:{method} = yes`
Example: 💵 [Payment: telephone cards](https://openstreetbrowser.org/#communication/n5184319690&map=18/-23.05047/-47.83621&categories=communication)
Wiki: https://wiki.openstreetmap.org/wiki/Key:payment
2. `generator:source = {value}`
Example: ⚡ [Generator source: hydro](https://openstreetbrowser.org/#power/w613967578&map=20/-23.42565/-47.59601&categories=power)
Wiki: https://wiki.openstreetmap.org/wiki/Key:generator:source

**Comment by plepe** [comment]
1. Like this: `"tag:payment:visa": "VISA"` (see "tag:diet" for comparison)

2. Like this `"tag:generator:source=hydro": "Hydro"` (it's just a normal tag/value system, there's just an additional colon in the tag name)

**Comment by IgorEliezer** [comment]
https://github.com/plepe/openstreetmap-tag-translations/pull/23

**Comment by plepe** [comment]
Here I added translating the payment options: plepe/openstreetbrowser-categories-main@363b6021b42ea1c93438c153c71ce887c0cff24a
