### ISSUE TITLE
xmas features support for Openstreetbrowser

### ISSUE THREAD

**Issue by lintux** [plepe/OpenStreetBrowser#57]
Hi,
looking at the https://be2art.de/xmasmap/ and the xmas features in OSM ( https://wiki.openstreetmap.org/wiki/DE:Key:xmas:feature ), I wonder if this would not be a good (temporary?) Category to add to Openstreetbrowser?

BR
Stephan

**Comment by plepe** [comment]
Absolutely! There even was a xmas category in a former version of OpenStreetBrowser. Maybe we should add a festivities main category?

Anyway, don't you want to create that category yourself? If it is ready "for production" I could merge it ...

**Comment by plepe** [comment]
I noticed that you might have had problems. I removed some unneeded code from your category (which was added by default) and fixed the embedded editor. I hope you have more luck now. If you need help, please say so!

**Comment by lintux** [comment]
Thanks .. I will try again once I find a quiet minute ..

**Comment by plepe** [comment]
The main categories now include a Xmas category: https://www.openstreetbrowser.org/#categories=xmas

If you have ideas for improvements, please post a new issue here: https://github.com/plepe/openstreetbrowser-categories-main/
