### ISSUE TITLE
Unnamed PT stops: use "no name" instead of node number

### ISSUE THREAD

**Issue by IgorEliezer** [plepe/OpenStreetBrowser#61]
Example: https://openstreetbrowser.org/#pt/r8757362&map=17/-23.03286/-47.83526&categories=pt

As you can see, the stop list shows unnamed stops as node number (e.g. n5942100640). It's kind of crypt for a normal user.

I think displaying "no name"instead would look better.

**Comment by plepe** [comment]
You are right, I changed this behaviour.

Fixed in plepe/openstreetbrowser-categories-main@7c98911738ac7bbc284f320ea7fc4ed47240246c
