### ISSUE TITLE
Translations for "Memorials" and "Energy" categories not available on site

### ISSUE THREAD

**Issue by IgorEliezer** [plepe/OpenStreetBrowser#62]
Hello, :wave: 

I'm not sure if "Culture:Memorials" and "Infrastructure:Energy" main categories are still on development. This PR https://github.com/plepe/openstreetbrowser-categories-main/pull/22 was merged 4 days ago but still is not up, while this PR https://github.com/plepe/openstreetmap-tag-translations/pull/24 is up already. It made me wonder.

BTW, OBS is awesome. Regards, :)

**Comment by plepe** [comment]
Thanks for your feedback :-) As I already wrote, I fixed it.
