### ISSUE TITLE
Enlarge the download data possibility 

### ISSUE THREAD

**Issue by severinmenard** [plepe/OpenStreetBrowser#63]
As far as I understood but I may be wrong, you can get JSON file only after clicking on a specific POI. Would be interesting to be able to download a whole category or everything currently displayed in the area on screen.

**Comment by plepe** [comment]
Yes, you are right. I will look into it. (Shouldn't be hard though)

**Comment by plepe** [comment]
This has finally been implemented: https://blog.openstreetbrowser.org/node/59

I hope everything works? Any ideas for improvements?

**Comment by severinmenard** [comment]
Great! The GeoJSON works fine in QGIS and we get all the attributes+metadata. You have maybe a duplicate with "id" and "@id"
I can help for the translations in French and Portuguese for the texts of the new Export toolbar (+ a few information bubbles)

**Comment by plepe** [comment]
Good to hear :-) I tried to use the same GeoJSON format as Overpass Turbo does - and they also have 'id' and 'properties.@id' ...

About the translations - yes, this would be great. You can find the new strings in these files: https://github.com/plepe/OpenStreetBrowser/tree/master/lang

More about translating OpenStreetBrowser:
https://wiki.openstreetmap.org/wiki/OpenStreetBrowser/Howto_translate
