### ISSUE TITLE
Category enhancement

### ISSUE THREAD

**Issue by lintux** [plepe/OpenStreetBrowser#65]
Hi,

I assume that https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpublic_bath is not yet in the list of managed tags. Could you please add it?

BR
Stephan

**Comment by plepe** [comment]
Sure. What category shall I add it to? I think it would fit into the Leisure category, although it would be the only map feature whose tag is not leisure=*.

**Comment by lintux** [comment]
I feared this question would come up. But leisure should be ok ...

Am 15. November 2018 17:52:47 MEZ schrieb "Stephan Bösch-Plepelits" <notifications@github.com>:

**Comment by plepe** [comment]
Hmm, maybe I should create a 'Water' resp. 'Swimming' resp. 'Bathing' category?

With:
* leisure=water_park
* amenity=public_path
* leisure=sports_centre sport=swimming
* leisure=swimming_pool
* leisure=sauna
* tourism=spa_resort
maybe others?

Question is, what is a suiting category title?

**Comment by lintux** [comment]
in the Wiki it's named as Swimming and bathing .. maybe that's it?
https://wiki.openstreetmap.org/wiki/Swimming_and_bathing
Interesting is also the amenity=public_path from above in this domain ;-)

**Comment by plepe** [comment]
If you are bored, you could add translations for the relevant tags. Also for English and your language (I guess you are German?):
https://github.com/plepe/openstreetmap-tag-translations/tree/master/tags

You can edit the files directly on Github!

**Comment by plepe** [comment]
For translation, it's using the tags from above + all `tag:bath:type` and `tag:sauna:type`.

**Comment by plepe** [comment]
I think, the category is now ready to use. I announced it today via blog, twitter and mastodon:
https://blog.openstreetbrowser.org/node/56

**Comment by IgorEliezer** [comment]
> I announced it today via blog, twitter and mastodon:

Why don't you publish a diary post at openstreetmap.org? ([Like I did](https://www.openstreetmap.org/user/IgorEliezer/diary/46831))

**Comment by plepe** [comment]
You are right, I just did that: https://www.openstreetmap.org/user/skunk/diary/47066

I will do that for future announcements as well :-)
