### ISSUE TITLE
Support maxspeed:forward & maxspeed:backward

### ISSUE THREAD

**Issue by mahdi1234** [plepe/OpenStreetBrowser#77]
Hi there,

road segments which are correctly marked as having different speed in opposite ways are shows as "Unknown" - it would very much help to distinguish such roads with different color and maybe tag "different speed each direction" so mapper can ignore those without going to details of a way.

https://wiki.openstreetmap.org/wiki/Forward_%26_backward,_left_%26_right

cheers,
mahdi

**Comment by plepe** [comment]
Thanks for your message! You are right, this is something I missed. I just fixed that: https://blog.openstreetbrowser.org/node/62

Hope you like it :-)

**Comment by mahdi1234** [comment]
Fantastic! :)
