### ISSUE TITLE
Residencial subtypes

### ISSUE THREAD

**Issue by IgorEliezer** [plepe/OpenStreetBrowser#79]
Whereas that there's a [category Residential](https://openstreetbrowser.org/#map=17/-23.04699/-47.84033&categories=residential) and `landuse=residential` can be broken into subtypes with [residential tag](https://wiki.openstreetmap.org/wiki/Tag:residential=urban), it would be nice if the pop-up and the left panel showed the value of residential tag.

Per [the wiki page](https://wiki.openstreetmap.org/wiki/Key:residential), I would support `urban`, `rural` and `gated` to start; [`university`](https://wiki.openstreetmap.org/wiki/Tag%3Aresidential%3Duniversity) seems not to be accepted and [halting_site](https://wiki.openstreetmap.org/wiki/FR:Aires_d%27accueil_des_gens_du_voyage) has a wiki page only in French. The others would fall in "others" category.

[The taginfo shows all the other values](https://taginfo.openstreetmap.org/keys/residential#values).

**Comment by plepe** [comment]
I just updated the category and created common entries in the translation file. It shows the residential type in the description in brackets, e.g. "(rural)".

Hope you like it :-)

**Comment by plepe** [comment]
About `residential=HDB`: This seems to be some special residential building type, see https://wiki.openstreetmap.org/wiki/WikiProject_Singapore#Buildings

It's quite common (2278 entries according to taginfo, plus 918 in lower case). That's why I added it to the list ...

**Comment by IgorEliezer** [comment]
> About residential=HDB

I saw that one too in the taginfo, but I didn't take it in consideration because it was quite [Singapore-centric](https://taginfo.openstreetmap.org/tags/residential=HDB#map). 

Thank you. :)

**Comment by plepe** [comment]
Yeah, I know. Do you think, I should remove it?
