### ISSUE TITLE
"agriculture" not translatable, in Building Types

### ISSUE THREAD

**Issue by IgorEliezer** [plepe/OpenStreetBrowser#80]
See: "Buildings" -> "Building Types", in the drop-down info menu, "agriculture" is not translatable.

![image](https://user-images.githubusercontent.com/4673289/51079855-d41c6380-16b6-11e9-8df3-c1e0bc990fc6.png)

openstreetmap-tag-translations is missing building=agricultural or building=agriculture, not sure if it's related.

**Comment by plepe** [comment]
Sorry for not looking into this earlier. I now added building=agriculture.
