### ISSUE TITLE
Map features do not appear in selected Data language

### ISSUE THREAD

**Issue by Juergeen** [plepe/OpenStreetBrowser#84]
While my Interface and Data languages are (by default) set to "English (English)", major cities like Moscow, Jerusalem or Cairo do not appear in English, but in Cyrillic, Hebrew or Arabic scripts. Because I was able to search for these cities with their English names, these must have been available as parts of the data set.

**Comment by plepe** [comment]
Where do the names appear? On the map background? That's not possible (right now), as I use the standard map tiles provided by openstreetmap.org .

You should see the English names, when use categories, e.g. Places -> Places.

**Comment by plepe** [comment]
I see. The background map is rendered as PNG images in 256x256px tiles and cached on the server side. This is very fast and well supported on the client-side, but it also has the problem that no modification of the image is possible.

There's work on so-called vector tiles, which could solve this problem and would also allow customized colors. It's interesting, but not ready-to-use.

**Comment by Juergeen** [comment]
Thank you.
By the way: Great work !
