### ISSUE TITLE
No Wikipedia images in some popups

### ISSUE THREAD

**Issue by Cybereric** [plepe/OpenStreetBrowser#85]
On some Wikipedia articles the first image of the article does not appear in the popup 

Example:  https://www.openstreetbrowser.org/#tourism_attractions/n3610328592/details&map=19/47.21450/-1.55834&categories=tourism_attractions

The article : https://fr.wikipedia.org/wiki/Place_Royale_(Nantes)

The file : https://commons.wikimedia.org/wiki/File:Nantes_-_fontaine_de_la_Place_Royale.jpg

I've found that it's because of the small seal present at the top right corner of the Wikimedia Commons page
This one : https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Valued_image_seal.svg/20px-Valued_image_seal.svg.png

It's the same for all wikipedia articles having a valued image as first image.

Is there any solution , a filter ?

**Comment by plepe** [comment]
I will look into it, there should be a solution. In this example I noticed another problem with the wikipedia integration: the `artist:wikipedia` tag has multiple values (separated by ;). This is not supported yet.

**Comment by plepe** [comment]
Just fixed all of the problems :-)

* The Wikipedia/Wikidata integration now supports multiple values (separated by ;)
* The Image parser works much better, icons should no longer appear

Also, I took the liberty to add some images to nearby objects: https://www.openstreetmap.org/changeset/74656446

If you notice more problems, please report them!
