### ISSUE TITLE
Height display

### ISSUE THREAD

**Issue by Cybereric** [plepe/OpenStreetBrowser#87]
When I put the tag "height=*" on an object I always put the units (example: 10 m) even if it's optional.
I just saw that in this case in OpenStreetBrowser it becomes "mm" as there is already an expected m !
See https://www.openstreetbrowser.org/#buildings-height/w28735810&map=18/47.21229/-1.56537&categories=buildings-height

And there should be a space between the number and the unit: 10m is bad while 10 m is good
[Height key on the wiki](https://wiki.openstreetmap.org/wiki/Key:height)
Actually there's no space
See https://www.openstreetbrowser.org/#buildings-height/w332647397&map=18/47.21722/-1.55745&categories=buildings-height

**Comment by plepe** [comment]
You are right. Just fixed this in plepe/openstreetbrowser-categories-main@a715d023219ebe6407ae3f3b0dba1a86d95165df .

It now also supports values in ft (e.g. "40 ft"). For calculating the color it will be converted to meters, but the original value will be shown.

Also, there's now a space. And a "," when both height and building:levels are set.
