### ISSUE TITLE
amenity=language_school not listed under "Education"

### ISSUE THREAD

**Issue by IgorEliezer** [plepe/OpenStreetBrowser#88]
This language school (https://www.openstreetmap.org/way/545262824) is not listed under "Education". 

See: https://openstreetbrowser.org/#map=20/-23.04475/-47.83469&categories=education

**Comment by plepe** [comment]
My mistake. I had it in the query from z14 to z15, but not from z16 on. Fixed in plepe/openstreetbrowser-categories-main@26c1b5e04641b9afad20535dd6a7e13c100becb9
