### ISSUE TITLE
Galician translation

### ISSUE THREAD

**Issue by IVAN-RSM** [plepe/OpenStreetBrowser#89]
I want to translate the application to Galician. Where is the translation portal like Weblate?

**Comment by plepe** [comment]
Currently I'm not using a translation portal, the JSON files are edited by hand: https://wiki.openstreetmap.org/wiki/OpenStreetBrowser/Howto_translate

Weblate looks really nice, I was looking for something like this. I will look into installing it for OpenStreetBrowser. I hope I can set it up in a few days, please stay tuned :-)

**Comment by IVAN-RSM** [comment]
So I start with the translation now or wait for that?

**Comment by plepe** [comment]
As you wish. Your contribution won't be wasted :-)

**Comment by plepe** [comment]
It's done! I just finished setting up Weblate. I really like it :-)

=> https://weblate.openstreetbrowser.org/projects/openstreetbrowser/

One module can't be translated via weblate, as it needs actual source code: https://github.com/plepe/openstreetmap-date-format

Have fun! If have have any comments, I'd like to hear them ...

**Comment by IVAN-RSM** [comment]
Oh thanks! I'll get to it these days :)

**Comment by plepe** [comment]
The galician translation is now online! Have fun.

Please be aware that I need to import the translations manually, so this always takes a day or so.
