### ISSUE TITLE
Some items appearing as wrong type

### ISSUE THREAD

**Issue by Fizzie41** [plepe/OpenStreetBrowser#91]
Some items are appearing under the wrong classification in OSB, despite being tagged correctly in OSM.

If you look here: https://www.openstreetbrowser.org/#map=17/-28.04861/153.43527&categories=leisure
you'll see that "Essence of Living" & "Coast to Coast Personal Training" are both listed under "Leisure" as fishing spots!

If you change the filter to "Sport" https://www.openstreetbrowser.org/#map=17/-28.04861/153.43527&categories=sport
they now appear correctly as yoga & fitness.

Should they also appear under "Health", or maybe not?

Thanks

Graeme

**Comment by plepe** [comment]
Oh, that was a problem with the English translation - I guess I must have made a copy&paste error when creating the strings for leisure=fitness_centre and leisure=dog_park. I now fixed that.

If you are interested, I'm always looking for translators, also for English: https://weblate.openstreetbrowser.org/projects/openstreetbrowser/

> Should they also appear under "Health", or maybe not?

No, I don't think that fitness centers are health institutions.

**Comment by Fizzie41** [comment]
Thanks

> If you are interested, I'm always looking for translators, also for English:

Unfortunately, I only speak English so can't help with any translations, although I'm more than happy to help with proof-reading.

Graeme

**Comment by plepe** [comment]
Oh, you can help alright. Check https://weblate.openstreetbrowser.org/projects/openstreetbrowser/osm-tags/ - in this component, only 34,6% of strings have an english translation. That's the names OpenStreetMap tags - as fallback the tag value is shown (e.g. "fitness_centre") which is not very nice -> it should read "Fitness Centre".

You are Australian, aren't you (guessing this from the link you sent)? Maybe you could also create an Australian translation, I guess there are some differences to British English, aren't there? You would only need to translate the strings which are different though ...
