### ISSUE TITLE
Longitudes not resetting at +- 180

### ISSUE THREAD

**Issue by InsertUser** [plepe/OpenStreetBrowser#92]
I am getting the following error in OpenStreetBrowser:

> Error loading data from Overpass API: line 1: static error: Longitudes in bounding boxes must be between -180.0 and 180.0. 

The URL is being displayed as:
https://openstreetbrowser.org/#map=14/-35.0012/-221.4191&categories=shop,craft

This is displaying for me if I scroll past the antimeridian in Chrome and Firefox under both Windows 10 and Android 9.

**Comment by plepe** [comment]
I knew that at some point someone will notice that I didn't take care of that.

I will look into this, but I guess this will take some time. I'll keep you updated!

**Comment by plepe** [comment]
Done!

https://blog.openstreetbrowser.org/node/68
