### ISSUE TITLE
Weblate

### ISSUE THREAD

**Issue by Cybereric** [plepe/OpenStreetBrowser#93]
Hello,
In Weblate there are strange things :
- First some source values are missing. See the image
  So in the list mode (when the value is not yet translated) all the line is blank.
  Is this usual or not ? 
![missing values](https://user-images.githubusercontent.com/7645549/53130101-a3f39a80-3569-11e9-94a3-ce7a42e3bc84.png)

- Secondly there is an error that says that the source and the translation are identical. 
  Many words are the same in french and english (ex : cuisine, religion, images, statue,...) so it's ok.
  How can I validate these translations? I did not find the function that allows that.
![same source and translation](https://user-images.githubusercontent.com/7645549/53130162-c685b380-3569-11e9-82ce-b03a1d7e7763.png)

**Comment by plepe** [comment]
1. Yes, that (unfortunately) an issue. Many strings don't have an English translation - instead the tag value will be shown, if the translation is empty. If you use the "normal" view, you will see the comment, which shows which tag is used and where in the OSM Wiki to find information about this string. In the list view this information is apparently missing. I wouldn't want to add the tag value as translation though.

What I could do, I could create a "template.json" file, which hold the tag-values as translation and use this as source file for translations. What do you think of this? I would use e.g. "amenity=restaurant" as template string.

2. German has the same issue, and I haven't found a way yet, how to verify these strings ...

**Comment by Cybereric** [comment]
About 1/
As I think I understood
If edit the source (english) field is it OK  and write the corresponding English word it'll make the missing english translation.
No ? 
So I can do that waiting to do a global translation for English

**Comment by plepe** [comment]
Yes, exactly :-)
