### ISSUE TITLE
Feature Request: Filter Natural Formations and other categories by Type

### ISSUE THREAD

**Issue by Aureuum** [plepe/OpenStreetBrowser#99]
Hello, I like your software a lot!
A feature that would be great would be if all categories could be filtered by type as well.
As of now, e.g. Services/Health can be filtered by type, but it would be great if e.g. Natural Formations could be filtered by type as well.
So, e.g. one could just see the beaches without having to display the whole coastline, capes etc.
Thanks much for considering this!
Jan

**Comment by plepe** [comment]
This will happen, it is just not there yet, because there are so many categories to update - the filters have to be created by hand, because each category is a little bit different.

I will prioritize Natural Formations, maybe I'll have time today to do that :-)

**Comment by IgorEliezer** [comment]
@plepe, let me ask you a question: I see the "Title" filter (the filter you type in) is not working in every category even if it's there  (e.g. &categories=leisure). This filter is working only in the categories which have both the "Type" filter and "Title" filter. Are you aware of it?

**Comment by Aureuum** [comment]
@plepe, thank you for your reply, that would be helpful!
Also, under a category like Shopping, or Services/Health, the sublist under Filter by Type comes up in random order, which makes it difficult to find an item in a large list. Would it be possible to order these lists alphabetically?
Also, I tried to install it on my XAMPP server, but didn't work, and I only see installation instructions for Ubuntu here. How does one install it on a Linux or XAMPP server?
Thank you very much!
Jan

**Comment by plepe** [comment]
I just pushed the updated 'natural formations' category, also an updated 'water bodies' category. I hope you like it. I'll describe the most important changes in a separate blog post (hopefully soon). As you can see, many formations even got an icon and a separate color. If you have suggestions for better colors and icons, please say so (see available icons [here](https://github.com/plepe/OpenStreetBrowser/blob/master/doc/Icons.md)).

About the ordering of items in the filter - I already had written a sorting routine, but haven't published it yet. It's now online :-)

**Comment by Aureuum** [comment]
Thank you, that's very helpful! :)
I notice in the ordered lists for filter Type, there are some capitalized items, which are not particular names of places, and this causes the list to be alphabetized twice, first for the capitalized items, and then for the lower case items.
Maybe it could be better to have all items, which are not names, just as lowercase, to get a cleaner looking list?
Also, under Shopping, I don't see grocery store, or food store. Is there not such a category available?

**Comment by plepe** [comment]
The lists will now be sorted case insensitive. The reason for the lower case items is, that these strings don't have an English translation yet (haven't found anyone who will take care of the English translation).

About shop: there's such a huge list of [available shop types](http://wiki.openstreetmap.org/wiki/Key:shop), that I haven't added all to the list of types yet (each type should have a separate icon). See here: https://github.com/plepe/openstreetbrowser-categories-main/blob/master/shop.json (feel free to add these types yourself and create a pull request, with a suiting icon when possible).
All shop types (regardless if they are listed or not) will be included in the category result though, they will just get some default icon (shopping bag).

Beaches: They are now colored coral.

**Comment by Aureuum** [comment]
Thank you, that works great with the sorting to be case insensitive.
And the beaches look great with coral color! :)
